### ISSUE TITLE
About connect RPi to control KK 2.1.5

### ISSUE THREAD

**Issue by quocthinhvo** [Nano-Elektron/Autonomous-Quad#1]
Hi bro,

I have watched your video and post at: https://thetechcache.science/raspberry-pi-driven-kk2-1-5-quadcopter. And I have tried it. But have some error. 

Details: 
- Raspberry Pi Zero W
- KK 2.1.5
- I have connect 11, 12, 15, 16 of GPIO in RPI -> 1, 2, 3, 4 in KK. I have marked the number of connection pins on the picture.
![image](https://user-images.githubusercontent.com/46624702/121796852-56256380-cc46-11eb-8f6b-ba2257f9c228.png)
- After that, I run pwm_mimic.py and press 'n' to armed KK. 
- The code show in screen: "quad successfully armed", but in KK is safe mode (not armed).

Please give for me more information to do it.

**Comment by quocthinhvo** [comment]
Please help me.

**Comment by quocthinhvo** [comment]
I did it

**Comment by holmesvinn** [comment]
> I did it

kindly comment the change that helped you if possible. thanks !
